### ISSUE TITLE
Failing uploading tracks

### ISSUE THREAD

**Issue by BCafGun** [Poniverse/Pony.fm#137]
I guess "unknown error" issue is back again :)
No tracks can be uploaded now. Judging by the main list of new tracks, it's massive issue, happened 5 days ago.

**Comment by SpikyDash** [comment]
It looks like it's still around because I'm running into similar issues today. Trying to upload, ran into the unknown error message every time on my desktop. Tried it on Chromebook and it gets stuck in processing. Haven't had these issues in quite some time so I don't know what the issue could possibly be. Have also reached out to support through email.

**Comment by omnicons** [comment]
Not the same issue. This new issue is related to the server migration we've undergone. We'll work on the server configuration some more, but the original issue from 2019 was resolved back then as we were having an issue with the storage server back then.

**Comment by SpikyDash** [comment]
Sounds good, thanks for the update. Much appreciated.
