### ISSUE TITLE
Search Web Service: HTTP 500 Error

### ISSUE THREAD

**Issue by Zian** [Poniverse/Pony.fm#158]
Steps to Reproduce:
1. Go to the home page
2. Click in the search text box
3. Type "jeff"
4. Press enter

Expected Result:
Search results

Actual Result:
HTTP 500 error. The Developer Tools console says:
XHR GET https://pony.fm/api/web/search?query=jeff
[HTTP/2 500 Internal Server Error 114ms]

**Comment by LavaToaster** [comment]
Thanks for the heads up @Zian! Turns out our elastic search server was down and we didn't know about it.

I've gave it a bit of a poke and it's back up now.

Usually we have monitoring for these sort of things and the search server was not on our list of things to monitor, so we'll add it to the list and hopefully we'll be able to fix it before you notice next time!
