### ISSUE TITLE
Is Pony.FM dead/going away permanently?

### ISSUE THREAD

**Issue by SpikyDash** [Poniverse/Pony.fm#213]
So I've been contributing my pony parodies to the site for a few years now, and I was just beginning to have a solid amount of success on the site. Now, I've been trying to check the site for the past few days and it is either completely down or an error message pops up saying "No connection - Pony.FM requires an internet connection to load." I knew my internet wasn't the issue because it loaded other sites fine, so I thought that this was a server issue [since Ponyville Live, who I know also runs off of Cloudflare, was having similar loading issues]. As it turned out, I got a Twitter response when I posted about these issues saying that the domain names were no longer paid for and are now in pending delete status. If they are not paid in 3 months, they will essentially disappear. So my question is, is this the end? Is the website and the corresponding sites that are owned by Poniverse essentially going to either die out or be put up for sale? I mean it would honestly be a bummer to find a new platform for my content after having such success here, but I'm just curious if anyone is aware that these issues are currently happening.

**Comment by thomcuddihy** [comment]
Hi Spiky,

Thanks for reaching out and your concern over the site, but the truth is a lot more mundane: simple human error. The last domain renewal was mistakeningly only renewed for a single year, instead of our standard two year cycles :)

We have already renewed the domain and are waiting on the registrar to finalise it, which should be within 36 hours. There are definitely no plans for retiring any Poniverse site currently.

Thanks again for reaching out, and for continuing to make content!

**Comment by SpikyDash** [comment]
Hi Thom,
Oh I can't tell you how happy this makes me!!! Thank you so much for getting back to me so quickly. I very much appreciate it and love the platform you have for content creators like myself in the fandom. Thanks again!

~SPIKY DASH

________________________________
