### ISSUE TITLE
Artists missing from artists pages

### ISSUE THREAD

**Issue by daniel-j** [Poniverse/Pony.fm#5]
When looking at the artists page https://pony.fm/artists there are many artists missing that can be found elsewhere on the site (find a track by that artist). For example https://pony.fm/4everfreebrony is not on the artists pages. I assume it has to do with the recent MLPMA import.
I did a quick script to compare the tracks pages with the artists pages and found out that there are about 100 missing artists.
Chatted with @Feld0 about it and his response about it was:
> It looks like this is caused by some artists not having their track count in the users table updated (and the MLPMA bypasses the usual publishing process which keeps that up to date).
> This can be fixed with a script to recount all artists' track counts.

**Comment by Feld0** [comment]
This can be fixed with a `rebuild:track-counts` [Artisan command](http://laravel.com/docs/5.1/artisan#writing-commands) which recounts every user's tracks.

The script will likely resemble [this one](https://github.com/Poniverse/Pony.fm/blob/master/app/Console/Commands/RebuildTags.php) for rewriting tags in track files.
