### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by logic-dev** [Poniverse/Pony.fm#79]
When viewing a user's page via the track page and pressing the back button, the browser goes back to the track page. However pressing the back button again will go back to the user page. Intended action, return to home page

**Comment by Feld0** [comment]
I narrowed this issue down to [this section of code](https://github.com/Poniverse/Pony.fm/blob/master/resources/assets/scripts/app/controllers/application.coffee#L73) - commenting out the block that starts at the highlighted line "fixes" it, but I'd like to figure out what's going on here and make a more... targeted fix.

**Comment by Feld0** [comment]
The fix turned out to be quite straightforward, as you can see in 824229b. Description of the "location" parameter from [UI-Router's docs](https://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$state):

> location - {boolean=true|string=} - If true will update the url in the location bar, if false will not. If string, must be "replace", which will update url and also replace last history record.

There's still flickering in the URL after initiating a state change (because we cancel it in `application.coffee` and then trigger a new state change with our own code) but refactoring that may be a task in itself.
